### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Kail0** [borisjoffe/facebook-event-export-button#1] opened 2018-06-17 14:21 UTC
Tried with no addons enabled. Firefox up to date.

**Comment by borisjoffe** [comment] 2018-06-23 08:59
I fixed three bugs caused by Facebook's code changes to the event page - one with the incorrect handling of certain types of addresses, one with the export button not working, and one with the handling of dates/times.

Can you update the script and see if it works now? If it doesn't, click the "About" tab on the event page, refresh the page, and wait about 5 seconds. If that still doesn't work, let me know and send me the link to the event page if possible.

**Comment by borisjoffe** [comment] 2018-07-07 03:38
I'm closing this issue - feel free to add a comment if the bug still exists

**Closed by borisjoffe** 2018-07-07 03:38 UTC
Labels: bug

**Comment by Kail0** [comment] 2018-07-13 07:29
Working. Thank you! (:
